# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=models.TextField(max_length=40960, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatar/default.png', upload_to='avatar', verbose_name='头像'),
        ),
    ]
