# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171124_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set([('article', 'user')]),
        ),
    ]
