# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171124_1536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set([('article', 'user', 'is_like')]),
        ),
    ]
