# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171124_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='反对次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
    ]
